CC=g++

CFLAGS=

OBJ_DIR=../../obj

NETSCILIB_ROOT_DIR=../../netscilib

BUILDING_BLOCK_SOURCES=$(NETSCILIB_ROOT_DIR)/data_structures_building_blocks/*.hpp

SOURCES=array_test.cpp

all:
	$(CC) $(CFLAGS) $(SOURCES) $(BUILDING_BLOCK_SOURCES) -o $(OBJ_DIR)/array_test